FROM python:3.10-slim

WORKDIR /app

COPY wheelhouse /wheelhouse
COPY requirements.txt .
RUN pip install --find-links=/wheelhouse -r requirements.txt

COPY . .

CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8000", "--server.address=0.0.0.0"]
